---
- name: Conf access switches
  hosts: switches
  

  tasks:

    - name: Configuracion banner
      ios_banner:
        banner: login
        text: |
          ********************************************************************
          *                                                                  *
          *                            ADVENTENCIA                           *
          *                                                                  *
          * El usuario se encuentra conectado a un dispositivo de la red de  *
          * EPN, este sistema es de uso exclusivo. El acceso esta autorizado *
          * solo para administradores del sistema con aprobacion por escrito.*
          * El acceso no autorizado queda prohibido y sera demandado,        *
          * la politica y estandar de la Direccion de Tecnologia es clara.   *
          *                                                                  *
          *                                                                  *
          *                              WARNING                             *
          *                                                                  *
          * The user is connected to a network device EPN, This system is    *
          * used exclusively by granted only for system administrators       *
          * with prior written a pproval. Unauthorized access is prohibited  *
          * and will be prosecuted. Policies and standards are clear         *
          * Technology Directorate.                                          *
          ********************************************************************
        state: present
    - name: Configuracion de interfaces
      ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/1
            access:
              vlan: 606
            
          - name: GigabitEthernet1/0/2
            access:
              vlan: 616
            
          - name: GigabitEthernet1/0/3
            access:
              vlan: 626
            
          - name: GigabitEthernet1/0/23
            trunk:
              native_vlan: 1
        state: merged
          



    