---
- name: Conf access switches
  hosts: switches
  tasks:
    - name: Configuracion banner
      ios_banner:
        banner: login
        text: |
          ********************************************************************
          *                                                                  *
          *                            ADVENTENCIA                           *
          *                                                                  *
          * El usuario se encuentra conectado a un dispositivo de la red de  *
          * EPN, este sistema es de uso exclusivo. El acceso esta autorizado *
          * solo para administradores del sistema con aprobacion por escrito.*
          * El acceso no autorizado queda prohibido y sera demandado,        *
          * la politica y estandar de la Direccion de Tecnologia es clara.   *
          *                                                                  *
          *                                                                  *
          *                              WARNING                             *
          *                                                                  *
          * The user is connected to a network device EPN, This system is    *
          * used exclusively by granted only for system administrators       *
          * with prior written a pproval. Unauthorized access is prohibited  *
          * and will be prosecuted. Policies and standards are clear         *
          * Technology Directorate.                                          *
          ********************************************************************
        state: present
    - name: Configure Multiple interfaces
      ios_config:
        parents: "{{ item }}"
        lines:
          - description Enlaces troncales
        after:
          - no shutdown
        save_when: modified
      with_items:
        - interface GigabitEthernet1/0/23
        - interface GigabitEthernet1/0/24
    - name: Configuracion de interfaces acceso
      ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/1
            access:
              vlan: 600            
          - name: GigabitEthernet1/0/2
            access:
              vlan: 600          
          - name: GigabitEthernet1/0/3
            access:
              vlan: 600
          - name: GigabitEthernet1/0/4
            access:
              vlan: 600
          - name: GigabitEthernet1/0/5
            access:
              vlan: 600
          - name: GigabitEthernet1/0/6
            access:
              vlan: 600
          - name: GigabitEthernet1/0/7
            access:
              vlan: 600
          - name: GigabitEthernet1/0/8
            access:
              vlan: 600
          - name: GigabitEthernet1/0/9
            access:
              vlan: 600
          - name: GigabitEthernet1/0/10
            access:
              vlan: 600
          - name: GigabitEthernet1/0/11
            access:
              vlan: 600
          - name: GigabitEthernet1/0/12
            access:
              vlan: 600
          - name: GigabitEthernet1/0/13
            access:
              vlan: 300
          - name: GigabitEthernet1/0/14
            access:
              vlan: 300
          - name: GigabitEthernet1/0/15
            access:
              vlan: 300
          - name: GigabitEthernet1/0/16
            access:
              vlan: 300
          - name: GigabitEthernet1/0/17
            access:
              vlan: 300
          - name: GigabitEthernet1/0/18
            access:
              vlan: 300
          - name: GigabitEthernet1/0/19
            access:
              vlan: 300
          - name: GigabitEthernet1/0/20
            access:
              vlan: 300
          - name: GigabitEthernet1/0/21
            access:
              vlan: 300
          - name: GigabitEthernet1/0/22
            access:
              vlan: 300
        state: merged
    - name: Configuracion de interfaz trunk
      ios_l2_interfaces:
        config:        
          - name: GigabitEthernet1/0/23
            trunk:
              native_vlan: 1
              allowed_vlans: 300,600
        state: merged
    - name: Create VLAN
      ios_vlans:
        config:
          - name: vlan_100
            vlan_id: 100
          - name: vlan_300
            vlan_id: 300
          - name: vlan_600
            vlan_id: 600
        state: merged
      register: vln
