---
- name: Obtener Informacion
  hosts: switches
  tasks:
    - name: Reune todos los facts
      ios_facts:
       gather_subset: all

    - name: Reune solo configuracion
      ios_facts:
        gather_subset:
        - config

    - name: No recolectar informacion de hardware
      ios_facts:
        gather_subset:
         - '!hardware'