---
- name: Obtener Informacion
  hosts: switches
  tasks:
    - name: Gather all legacy facts
      cisco.ios.ios_facts:
       gather_subset: all

    - name: Gather only the config and default facts
      cisco.ios.ios_facts:
        gather_subset:
        - config

    - name: Do not gather hardware facts
      cisco.ios.ios_facts:
        gather_subset:
         - '!hardware'

    - name: Gather legacy and resource facts
      cisco.ios.ios_facts:
        gather_subset: all
        gather_network_resources: all
